n=input('enter text to write to the file:')
file=open('output.txt','w')
file.write(n)
print('data successfully written to uotput.txt.')
a=input('enter additional text to append:')
file=open('output.txt','a')
file.write(a)
print('data successfully appended.')
file=open('output.txt','r')
result=file.read()
print("final content of the output")
print(result)

file.close()